# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e206bd83db05cef4ecd94903d0e9313acb5c1619bc778966a85dcbdbf3fcb10474d01ebcf6d9aafc3bd4839ba292dccf4d92a46b5f173aeef61bc8bb65822b19

test:
  secret_key_base: 6309e72a688e751fa3cb0a70d3e100a0f1a05a6cd885fd0562d8b15baf2a8ab81661dc7a7aeeb7cfb0a52350ad6115560ea718b8102bdb6829af6c9d90f3450c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
